# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('flight_number', models.CharField(default='0000', max_length=50)),
                ('airlines', models.CharField(default='default airlines', max_length=50)),
                ('image_url', models.CharField(default='img/default.jpg', max_length=256)),
                ('description', models.CharField(default='default flight description', max_length=500)),
                ('airplane', models.CharField(default='default airplane', max_length=50)),
                ('departure_airport', models.CharField(default='DFL', max_length=50)),
                ('arrival_airport', models.CharField(default='DFL', max_length=3)),
                ('cost', models.CharField(default='99999 рублей', max_length=20)),
                ('participation', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flights',
            },
        ),
    ]
